import type { Metadata } from 'next';
import { Inter, Anton } from 'next/font/google';
import './globals.css';

// define fonts in nextjs rules
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const anton = Anton({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-anton',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${anton.variable}`}>{children}</body>
    </html>
  );
}
